#ifndef MK1MF_BUILD
    /* auto-generated by util/mkbuildinf.pl for crypto/cversion.c */
    #define CFLAGS cflags
    /*
     * Generate CFLAGS as an array of individual characters. This is a
     * workaround for the situation where CFLAGS gets too long for a C90 string
     * literal
     */
    static const char cflags[] = {
        'c','o','m','p','i','l','e','r',':',' ','a','a','r','c','h','6','4','-',
        'l','i','n','u','x','-','a','n','d','r','o','i','d','-','g','c','c',' ',
        '-','-','s','y','s','r','o','o','t','=','/','U','s','e','r','s','/','s',
        't','a','f','f','/','D','o','c','u','m','e','n','t','s','/','w','o','r',
        'k','s','o','f','t','/','a','n','d','r','o','i','d','-','n','d','k','-',
        'r','1','3','/','p','l','a','t','f','o','r','m','s','/','a','n','d','r',
        'o','i','d','-','2','1','/','a','r','c','h','-','a','r','m','6','4',' ',
        '-','I','.',' ','-','I','.','.',' ','-','I','.','.','/','i','n','c','l',
        'u','d','e',' ',' ','-','f','p','i','c',' ','-','f','f','u','n','c','t',
        'i','o','n','-','s','e','c','t','i','o','n','s',' ',' ','-','f','u','n',
        'w','i','n','d','-','t','a','b','l','e','s',' ',' ','-','f','s','t','a',
        'c','k','-','p','r','o','t','e','c','t','o','r',' ',' ','-','n','o','-',
        'c','a','n','o','n','i','c','a','l','-','p','r','e','f','i','x','e','s',
        ' ','-','I','/','U','s','e','r','s','/','s','t','a','f','f','/','D','o',
        'c','u','m','e','n','t','s','/','c','o','c','o','s','2','d','x','l','i',
        'b','/','c','o','c','o','s','2','d','-','x','-','3','r','d','-','p','a',
        'r','t','y','-','l','i','b','s','-','s','r','c','/','c','o','n','t','r',
        'i','b','/','i','n','s','t','a','l','l','-','a','n','d','r','o','i','d',
        '/','a','r','m','6','4','/','i','n','c','l','u','d','e',' ','-','O','3',
        ' ','-','D','N','D','E','B','U','G',' ','\0'
    };
    #define PLATFORM "platform: os/compiler"
    #define DATE "built on: Tue Feb  8 10:37:31 2022"
#endif
